// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSZp9PGJCHodbwLaTAUtK0Nvy3ZZRayQo',
    appId: '1:969716314710:web:3e94efaa41807ff97c41f7',
    messagingSenderId: '969716314710',
    projectId: 'currecyapp',
    authDomain: 'currecyapp.firebaseapp.com',
    storageBucket: 'currecyapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkSNMdwsYh35oSXNx047h38k7pj0Npuks',
    appId: '1:969716314710:android:98ac102883a601a27c41f7',
    messagingSenderId: '969716314710',
    projectId: 'currecyapp',
    storageBucket: 'currecyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ESjnJwQC6rgML0AhbOpgXi168oDeLEY',
    appId: '1:969716314710:ios:428840a38a9dd9a57c41f7',
    messagingSenderId: '969716314710',
    projectId: 'currecyapp',
    storageBucket: 'currecyapp.appspot.com',
    androidClientId: '969716314710-6cj3p1pq6lfqvs0u4k53m46j3teja5ed.apps.googleusercontent.com',
    iosClientId: '969716314710-935ljq2itsrs0e50tc42cch7bh3qddiv.apps.googleusercontent.com',
    iosBundleId: 'n',
  );
}
